FROM golang:1.23-alpine
LABEL id="conjur-opentelemetry-tracer-junit-processor"
LABEL maintainer="CyberArk Software Ltd."

WORKDIR /test

RUN apk add -u curl \
               gcc \
               git \
               mercurial \
               musl-dev \
               bash

RUN go install github.com/jstemmer/go-junit-report@latest
