FROM golang:1.23-alpine
LABEL id="conjur-opentelemetry-tracer-test-runner"
LABEL maintainer="CyberArk Software Ltd."

ENTRYPOINT [ "go", "test", "-v", "-timeout", "3m" ]
WORKDIR /conjur-opentelemetry-tracer

RUN apk add -u curl \
               gcc \
               git \
               mercurial \
               musl-dev

COPY go.mod go.sum /conjur-opentelemetry-tracer/

RUN go mod download

COPY . .
