FROM golang:1.22-alpine
MAINTAINER CyberArk Software Ltd.
LABEL id="conjur-opentelemetry-tracer-junit-processor"

WORKDIR /test

RUN apk add -u curl \
               gcc \
               git \
               mercurial \
               musl-dev \
               bash

RUN go install github.com/jstemmer/go-junit-report@latest
